export const ROLES = Object.freeze({
  ADMIN: 1,
  CAJERA: 2,
  COCINA: 3,
  TRABAJADOR: 4
})

export const ROLES_CAJA = [ROLES.ADMIN, ROLES.CAJERA]
export const ROLES_INVENTARIO = [ROLES.ADMIN, ROLES.COCINA]
export const ROLES_TRABAJADOR = [ROLES.CAJERA, ROLES.COCINA, ROLES.TRABAJADOR]
